version: "3.9"
services:
  url-shortener-local-memory:
    image: url-shortener
    build: .
    ports: ["8082:8082"]
    environment:
      CONFIG_PATH: "./config/local-memory.yaml"
    restart: always

  url-shortener-local-postgres:
    image: url-shortener
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports: ["8082:8082"]
    environment:
      CONFIG_PATH: "./config/local-postgres.yaml"
      DATABASE_URL: "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-url_shortener}?sslmode=disable"

  postgres:
    image: postgres:latest
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-url_shortener}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-url_shortener}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata: