version: "3.8"
services:
  url-shortener:
    image: url-shortener
    ports:
      - "8082:8082"
    environment:
      STORAGE_TYPE: postgres
      DATABASE_URL: "postgres://myuser:mypassword@db:5432/url_shortener?sslmode=disable"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: